FROM yomorun/quic-mqtt:latest

WORKDIR $GOPATH/src/github.com/yomorun/yomo-source-mqtt-starter
COPY . .
RUN go get -d -v ./...
WORKDIR $GOPATH/src/github.com/yomorun/yomo-source-mqtt-starter/cmd/emitter/

CMD ["sh", "-c", "go run main.go"]
