version: '3.5'

services:

  noise-sink:
    image: local/noise-sink:latest
    container_name: noise-sink
    restart: always
    command: ["sh", "-c", "go run main.go"]
    ports:
      - "80:8000"
    networks:
      - noisenet

  noise-web:
    image: local/noise-web:latest
    container_name: noise-web
    restart: always
    command: ["sh", "-c", "yarn start"]
    ports:
      - "3000:3000"
    #extra_hosts:
    #  - "yomo.cel-la.store:127.0.0.1"
    links:
      - noise-sink
    depends_on:
      - noise-sink
    networks:
      - noisenet

  noise-flow:
    image: local/noise-flow:latest
    container_name: noise-flow
    restart: always
    command: ["sh", "-c", "yomo run ./cmd/flow/app.go -p 4242"]
    networks:
      - noisenet

  noise-zipper:
    image: local/noise-zipper:latest
    container_name: noise-zipper
    restart: always
    command: ["sh", "-c", "yomo wf run workflow.yaml"]
    links:
      - noise-flow
      - noise-sink
    depends_on:
      - noise-flow
      - noise-sink
    networks:
      - noisenet

  noise-source:
    image: local/noise-source:latest
    container_name: noise-source
    restart: always
    command: ["sh", "-c", "go run main.go"]
    environment:
      - YOMO_SOURCE_MQTT_ZIPPER_ADDR=noise-zipper:9999
      - YOMO_SOURCE_MQTT_SERVER_ADDR=0.0.0.0:1883
    links:
      - noise-zipper
    depends_on:
      - noise-zipper
    networks:
      - noisenet

  noise-emit:
    image: local/noise-emit:latest
    container_name: noise-emit
    restart: always
    command: ["sh", "-c", "go run ./cmd/emitter/main.go"]
    environment:
      - YOMO_SOURCE_MQTT_BROKER_ADDR=tcp://noise-source:1883
    links:
      - noise-source
    depends_on:
      - noise-source
    networks:
      - noisenet

networks:
  noisenet:
    driver: bridge